/**
 * Mapping from French country names (uppercase) to Unicode flag emojis.
 * The `pays` field in the database stores country names in French, often in uppercase.
 */
const COUNTRY_FLAGS: Record<string, string> = {
  // Afrique du Nord & Moyen-Orient
  'ALGERIE': '🇩🇿',
  'ALGÉRIE': '🇩🇿',
  'MAROC': '🇲🇦',
  'TUNISIE': '🇹🇳',
  'LIBYE': '🇱🇾',
  'EGYPTE': '🇪🇬',
  'ÉGYPTE': '🇪🇬',
  'MAURITANIE': '🇲🇷',
  'SOUDAN': '🇸🇩',
  'JORDANIE': '🇯🇴',
  'LIBAN': '🇱🇧',
  'SYRIE': '🇸🇾',
  'IRAK': '🇮🇶',
  'IRAN': '🇮🇷',
  'ARABIE SAOUDITE': '🇸🇦',
  'EMIRATS ARABES UNIS': '🇦🇪',
  'ÉMIRATS ARABES UNIS': '🇦🇪',
  'KOWEÏT': '🇰🇼',
  'KOWEIT': '🇰🇼',
  'QATAR': '🇶🇦',
  'BAHREÏN': '🇧🇭',
  'BAHREIN': '🇧🇭',
  'OMAN': '🇴🇲',
  'YEMEN': '🇾🇪',
  'YÉMEN': '🇾🇪',
  'ISRAEL': '🇮🇱',
  'ISRAËL': '🇮🇱',
  'PALESTINE': '🇵🇸',
  'TURQUIE': '🇹🇷',

  // Europe de l'Ouest
  'FRANCE': '🇫🇷',
  'ALLEMAGNE': '🇩🇪',
  'ITALIE': '🇮🇹',
  'ESPAGNE': '🇪🇸',
  'PORTUGAL': '🇵🇹',
  'BELGIQUE': '🇧🇪',
  'PAYS-BAS': '🇳🇱',
  'HOLLANDE': '🇳🇱',
  'LUXEMBOURG': '🇱🇺',
  'SUISSE': '🇨🇭',
  'AUTRICHE': '🇦🇹',
  'ROYAUME-UNI': '🇬🇧',
  'ANGLETERRE': '🇬🇧',
  'GRANDE-BRETAGNE': '🇬🇧',
  'IRLANDE': '🇮🇪',
  'DANEMARK': '🇩🇰',
  'SUEDE': '🇸🇪',
  'SUÈDE': '🇸🇪',
  'NORVEGE': '🇳🇴',
  'NORVÈGE': '🇳🇴',
  'FINLANDE': '🇫🇮',
  'ISLANDE': '🇮🇸',
  'GRECE': '🇬🇷',
  'GRÈCE': '🇬🇷',
  'CHYPRE': '🇨🇾',
  'MALTE': '🇲🇹',

  // Europe de l'Est & Centrale
  'POLOGNE': '🇵🇱',
  'REPUBLIQUE TCHEQUE': '🇨🇿',
  'RÉPUBLIQUE TCHÈQUE': '🇨🇿',
  'SLOVAQUIE': '🇸🇰',
  'HONGRIE': '🇭🇺',
  'ROUMANIE': '🇷🇴',
  'BULGARIE': '🇧🇬',
  'SLOVENIE': '🇸🇮',
  'SLOVÉNIE': '🇸🇮',
  'CROATIE': '🇭🇷',
  'SERBIE': '🇷🇸',
  'BOSNIE-HERZEGOVINE': '🇧🇦',
  'MACEDOINE': '🇲🇰',
  'ALBANIE': '🇦🇱',
  'MONTENEGRO': '🇲🇪',
  'ESTONIE': '🇪🇪',
  'LETTONIE': '🇱🇻',
  'LITUANIE': '🇱🇹',
  'RUSSIE': '🇷🇺',
  'UKRAINE': '🇺🇦',
  'BIELORUSSIE': '🇧🇾',
  'BIÉLORUSSIE': '🇧🇾',
  'REPUBLIQUE DU BELARUS': '🇧🇾',
  'BELARUS': '🇧🇾',
  'MOLDAVIE': '🇲🇩',
  'GEORGIE': '🇬🇪',
  'GÉORGIE': '🇬🇪',
  'ARMENIE': '🇦🇲',
  'ARMÉNIE': '🇦🇲',
  'AZERBAIDJAN': '🇦🇿',
  'AZERBAÏDJAN': '🇦🇿',
  'KAZAKHSTAN': '🇰🇿',
  'OUZBEKISTAN': '🇺🇿',
  'OUZBÉKISTAN': '🇺🇿',

  // Amériques
  'ETATS-UNIS': '🇺🇸',
  'ÉTATS-UNIS': '🇺🇸',
  'USA': '🇺🇸',
  'CANADA': '🇨🇦',
  'MEXIQUE': '🇲🇽',
  'BRESIL': '🇧🇷',
  'BRÉSIL': '🇧🇷',
  'ARGENTINE': '🇦🇷',
  'CHILI': '🇨🇱',
  'COLOMBIE': '🇨🇴',
  'VENEZUELA': '🇻🇪',
  'PEROU': '🇵🇪',
  'PÉROU': '🇵🇪',
  'CUBA': '🇨🇺',

  // Asie & Océanie
  'CHINE': '🇨🇳',
  'INDE': '🇮🇳',
  'JAPON': '🇯🇵',
  'COREE DU SUD': '🇰🇷',
  'CORÉE DU SUD': '🇰🇷',
  'REPUBLIQUE DE COREE': '🇰🇷',
  'REPUBLIQUE DE CORÉE': '🇰🇷',
  'COREE': '🇰🇷',
  'CORÉE': '🇰🇷',
  'TAIWAN': '🇹🇼',
  'HONG KONG': '🇭🇰',
  'SINGAPOUR': '🇸🇬',
  'MALAYSIA': '🇲🇾',
  'MALAISIE': '🇲🇾',
  'INDONESIE': '🇮🇩',
  'INDONÉSIE': '🇮🇩',
  'PHILIPPINES': '🇵🇭',
  'VIETNAM': '🇻🇳',
  'VIET NAM': '🇻🇳',
  'THAÏLANDE': '🇹🇭',
  'THAILANDE': '🇹🇭',
  'PAKISTAN': '🇵🇰',
  'BANGLADESH': '🇧🇩',
  'SRI LANKA': '🇱🇰',
  'AUSTRALIE': '🇦🇺',
  'NOUVELLE-ZELANDE': '🇳🇿',
  'NOUVELLE-ZÉLANDE': '🇳🇿',

  // Afrique subsaharienne
  'AFRIQUE DU SUD': '🇿🇦',
  'NIGERIA': '🇳🇬',
  'NIGÉRIA': '🇳🇬',
  'KENYA': '🇰🇪',
  'GHANA': '🇬🇭',
  'ETHIOPIE': '🇪🇹',
  'ÉTHIOPIE': '🇪🇹',
  'SENEGAL': '🇸🇳',
  'SÉNÉGAL': '🇸🇳',
  "COTE D'IVOIRE": '🇨🇮',
  "CÔTE D'IVOIRE": '🇨🇮',
  'CAMEROUN': '🇨🇲',
  'MALI': '🇲🇱',
  'BURKINA FASO': '🇧🇫',
  'NIGER': '🇳🇪',
  'GUINEE': '🇬🇳',
  'GUINÉE': '🇬🇳',
  'TANZANIE': '🇹🇿',
  'ANGOLA': '🇦🇴',
  'MOZAMBIQUE': '🇲🇿',
  'ZIMBABWE': '🇿🇼',
  'MADAGASCAR': '🇲🇬',
}

/**
 * Returns the flag emoji for a given country name (in French).
 * The lookup is case-insensitive and trims whitespace.
 * Returns an empty string if no flag is found.
 */
export function getCountryFlag(pays: string | null | undefined): string {
  if (!pays) return ''
  const normalized = pays.trim().toUpperCase()
  return COUNTRY_FLAGS[normalized] ?? ''
}
